name: Linux Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CONFIGURE_PRESET: linux
  BUILD_PRESET: linux-release
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install LLVM Clang-19
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 19

    - name: Set Clang as default
      run: |
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-19 100
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-19 100

    - name: Configure CMake
      run: CC=clang-19 CXX=clang++-19 cmake --preset ${{env.CONFIGURE_PRESET}}

    - name: Build
      run: cmake --build --preset ${{env.BUILD_PRESET}}
